spring:
  batch:
    table-prefix: mmall
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mmall?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  session:
    store-type: redis



UserPasswordSalt:
  mmall